[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.2"

# Optional: keep this if you're using Netlify CLI locally
[dev]
  command = "next dev"

[[redirects]]
  from = "https://adhokpro.com/*"
  to = "https://app.adhokpro.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/waitlist"
  status = 200
  conditions = { Host = ["adhokpro.com"] }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://app.adhokpro.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

[[plugins]]
  package = "@netlify/next"
  