[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.8"

[dev]
  command = "next dev"

[[redirects]]
# Only redirect if someone visits adhokpro.com directly and your DNS points here — remove to let GoDaddy handle
# from = "/" → removed intentionally

[[redirects]]
  from = "https://adhokpro.com/*"
  to = "https://app.adhokpro.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self' https://app.adhokpro.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

[[plugins]]
  package = "@netlify/plugin-nextjs"
